export const d = [
  {
    marketName: "Match Odds",
    marketId: "1.214006168",
    isMarketDataDelayed: true,
    status: "OPEN",
    betDelay: 0,
    bspReconciled: false,
    complete: true,
    inplay: false,
    numberOfWinners: 1,
    numberOfRunners: 2,
    numberOfActiveRunners: 2,
    lastMatchTime: "2023-05-19T05:12:33.605Z",
    totalMatched: 19184.22,
    totalAvailable: 8783.79,
    crossMatching: true,
    runnersVoidable: false,
    version: 5251193071,
    runners: [
      {
        selectionId: 39992,
        handicap: 0,
        status: "ACTIVE",
        lastPriceTraded: 2.36,
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 2.32, size: 372.35 },
            { price: 2.3, size: 102.55 },
            { price: 2.06, size: 213.41 },
          ],
          availableToLay: [
            { price: 2.36, size: 28.22 },
            { price: 2.38, size: 32.64 },
            { price: 2.4, size: 34.77 },
          ],
          tradedVolume: [],
        },
      },
      {
        selectionId: 39988,
        handicap: 0,
        status: "ACTIVE",
        lastPriceTraded: 1.74,
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 1.73, size: 83.41 },
            { price: 1.72, size: 37.33 },
            { price: 1.71, size: 179.5 },
          ],
          availableToLay: [
            { price: 1.75, size: 158.67 },
            { price: 1.76, size: 423.02 },
            { price: 1.77, size: 55.89 },
          ],
          tradedVolume: [],
        },
      },
    ],
    eventName: "Fremantle v Geelong",
  },
  {
    marketName: "First Scoring Play",
    marketId: "1.214006169",
    isMarketDataDelayed: true,
    status: "OPEN",
    betDelay: 0,
    bspReconciled: false,
    complete: true,
    inplay: false,
    numberOfWinners: 1,
    numberOfRunners: 4,
    numberOfActiveRunners: 4,
    totalMatched: 0,
    totalAvailable: 624.62,
    crossMatching: true,
    runnersVoidable: false,
    version: 5251193073,
    runners: [
      {
        selectionId: 762250,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 3.6, size: 78.32 },
            { price: 1.07, size: 26.02 },
          ],
          availableToLay: [
            { price: 8, size: 34.71 },
            { price: 15, size: 3 },
          ],
          tradedVolume: [],
        },
      },
      {
        selectionId: 762251,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 3.75, size: 74.04 },
            { price: 1.15, size: 24.89 },
            { price: 1.07, size: 11.68 },
          ],
          availableToLay: [
            { price: 8.6, size: 32.79 },
            { price: 15, size: 1 },
          ],
          tradedVolume: [],
        },
      },
      {
        selectionId: 740103,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 3.05, size: 99.33 },
            { price: 1.07, size: 37.54 },
          ],
          availableToLay: [
            { price: 5.7, size: 48.71 },
            { price: 15, size: 2 },
          ],
          tradedVolume: [],
        },
      },
      {
        selectionId: 740104,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 3.6, size: 78.32 },
            { price: 1.15, size: 24.89 },
            { price: 1.07, size: 11.68 },
          ],
          availableToLay: [
            { price: 8, size: 34.71 },
            { price: 15, size: 1 },
          ],
          tradedVolume: [],
        },
      },
    ],
    eventName: "Fremantle v Geelong",
  },
  {
    marketName: "First Goalscorer",
    marketId: "1.214006170",
    isMarketDataDelayed: true,
    status: "OPEN",
    betDelay: 0,
    bspReconciled: false,
    complete: true,
    inplay: false,
    numberOfWinners: 1,
    numberOfRunners: 16,
    numberOfActiveRunners: 16,
    totalMatched: 0,
    totalAvailable: 15.3,
    crossMatching: false,
    runnersVoidable: true,
    version: 5251193075,
    runners: [
      {
        selectionId: 25207396,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [{ price: 14, size: 15.31 }],
          availableToLay: [],
          tradedVolume: [],
        },
      },
    ],
    eventName: "Fremantle v Geelong",
  },
  {
    marketName: "First Quarter Result",
    marketId: "1.214006171",
    isMarketDataDelayed: true,
    status: "OPEN",
    betDelay: 0,
    bspReconciled: false,
    complete: true,
    inplay: false,
    numberOfWinners: 1,
    numberOfRunners: 2,
    numberOfActiveRunners: 2,
    totalMatched: 0,
    totalAvailable: 907.07,
    crossMatching: true,
    runnersVoidable: false,
    version: 5251193077,
    runners: [
      {
        selectionId: 39992,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [{ price: 2, size: 203.64 }],
          availableToLay: [{ price: 2.34, size: 213.93 }],
          tradedVolume: [],
        },
      },
      {
        selectionId: 39988,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [{ price: 1.75, size: 285.85 }],
          availableToLay: [{ price: 2, size: 203.64 }],
          tradedVolume: [],
        },
      },
    ],
    eventName: "Fremantle v Geelong",
  },
  {
    marketName: "Half Time Result",
    marketId: "1.214006172",
    isMarketDataDelayed: true,
    status: "OPEN",
    betDelay: 0,
    bspReconciled: false,
    complete: true,
    inplay: false,
    numberOfWinners: 1,
    numberOfRunners: 2,
    numberOfActiveRunners: 2,
    totalMatched: 0,
    totalAvailable: 903.02,
    crossMatching: true,
    runnersVoidable: false,
    version: 5251193079,
    runners: [
      {
        selectionId: 2013687,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [{ price: 2.08, size: 188.54 }],
          availableToLay: [{ price: 2.42, size: 211.77 }],
          tradedVolume: [],
        },
      },
      {
        selectionId: 2013667,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [{ price: 1.71, size: 299.52 }],
          availableToLay: [{ price: 1.93, size: 203.2 }],
          tradedVolume: [],
        },
      },
    ],
    eventName: "Fremantle v Geelong",
  },
  {
    marketName: "Half Time/Full Time",
    marketId: "1.214006173",
    isMarketDataDelayed: true,
    status: "OPEN",
    betDelay: 0,
    bspReconciled: false,
    complete: true,
    inplay: false,
    numberOfWinners: 1,
    numberOfRunners: 5,
    numberOfActiveRunners: 5,
    totalMatched: 0,
    totalAvailable: 512.84,
    crossMatching: true,
    runnersVoidable: false,
    version: 5251193081,
    runners: [
      {
        selectionId: 419396,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [{ price: 2.9, size: 107.18 }],
          availableToLay: [{ price: 5.2, size: 44.29 }],
          tradedVolume: [],
        },
      },
      {
        selectionId: 426986,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [{ price: 6.6, size: 36.35 }],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 426987,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [{ price: 8.6, size: 26.78 }],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 419398,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [{ price: 2.02, size: 199.64 }],
          availableToLay: [{ price: 2.9, size: 79.42 }],
          tradedVolume: [],
        },
      },
      {
        selectionId: 413426,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [{ price: 24, size: 18.69 }],
          availableToLay: [],
          tradedVolume: [],
        },
      },
    ],
    eventName: "Fremantle v Geelong",
  },
  {
    marketName: "Total Game Score",
    marketId: "1.214006174",
    isMarketDataDelayed: true,
    status: "OPEN",
    betDelay: 0,
    bspReconciled: false,
    complete: true,
    inplay: false,
    numberOfWinners: 1,
    numberOfRunners: 9,
    numberOfActiveRunners: 9,
    totalMatched: 0,
    totalAvailable: 0,
    crossMatching: true,
    runnersVoidable: false,
    version: 5251193083,
    runners: [],
    eventName: "Fremantle v Geelong",
  },
  {
    marketName: "Tri Bet",
    marketId: "1.214006175",
    isMarketDataDelayed: true,
    status: "OPEN",
    betDelay: 0,
    bspReconciled: false,
    complete: true,
    inplay: false,
    numberOfWinners: 1,
    numberOfRunners: 3,
    numberOfActiveRunners: 3,
    totalMatched: 0,
    totalAvailable: 0,
    crossMatching: true,
    runnersVoidable: false,
    version: 5251193085,
    runners: [],
    eventName: "Fremantle v Geelong",
  },
  {
    marketName: "Winning Margin 24.5",
    marketId: "1.214006176",
    isMarketDataDelayed: true,
    status: "OPEN",
    betDelay: 0,
    bspReconciled: false,
    complete: true,
    inplay: false,
    numberOfWinners: 1,
    numberOfRunners: 5,
    numberOfActiveRunners: 5,
    totalMatched: 0,
    totalAvailable: 0,
    crossMatching: true,
    runnersVoidable: false,
    version: 5251193087,
    runners: [],
    eventName: "Fremantle v Geelong",
  },
  {
    marketName: "Winning Margin 39.5",
    marketId: "1.214006177",
    isMarketDataDelayed: true,
    status: "OPEN",
    betDelay: 0,
    bspReconciled: false,
    complete: true,
    inplay: false,
    numberOfWinners: 1,
    numberOfRunners: 5,
    numberOfActiveRunners: 5,
    totalMatched: 0,
    totalAvailable: 84.99,
    crossMatching: true,
    runnersVoidable: false,
    version: 5251193089,
    runners: [
      {
        selectionId: 875065,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [{ price: 2.44, size: 45 }],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 875081,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [{ price: 2, size: 40 }],
          availableToLay: [],
          tradedVolume: [],
        },
      },
    ],
    eventName: "Fremantle v Geelong",
  },
  {
    marketName: "Winning Margin Spread",
    marketId: "1.214006178",
    isMarketDataDelayed: true,
    status: "OPEN",
    betDelay: 0,
    bspReconciled: false,
    complete: true,
    inplay: false,
    numberOfWinners: 1,
    numberOfRunners: 9,
    numberOfActiveRunners: 9,
    totalMatched: 0,
    totalAvailable: 299.76,
    crossMatching: true,
    runnersVoidable: false,
    version: 5251193091,
    runners: [
      {
        selectionId: 9354504,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [{ price: 1.27, size: 36.22 }],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 9354505,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [{ price: 1.27, size: 36.22 }],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 9354506,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [{ price: 1.27, size: 36.22 }],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 9354507,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [{ price: 1.27, size: 36.22 }],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 9354524,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [{ price: 1.27, size: 36.22 }],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 9354525,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [],
          availableToLay: [{ price: 4.6, size: 10 }],
          tradedVolume: [],
        },
      },
      {
        selectionId: 9354526,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [{ price: 1.27, size: 36.22 }],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 9354527,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [{ price: 1.27, size: 36.22 }],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 39993,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [{ price: 1.27, size: 36.22 }],
          availableToLay: [],
          tradedVolume: [],
        },
      },
    ],
    eventName: "Fremantle v Geelong",
  },
  {
    marketName: "Most Disposals - Group A",
    marketId: "1.214006179",
    isMarketDataDelayed: true,
    status: "OPEN",
    betDelay: 0,
    bspReconciled: false,
    complete: true,
    inplay: false,
    numberOfWinners: 1,
    numberOfRunners: 8,
    numberOfActiveRunners: 8,
    totalMatched: 0,
    totalAvailable: 0,
    crossMatching: false,
    runnersVoidable: false,
    version: 5251193093,
    runners: [],
    eventName: "Fremantle v Geelong",
  },
  {
    marketName: "Handicap",
    marketId: "1.214006180",
    isMarketDataDelayed: true,
    status: "OPEN",
    betDelay: 0,
    bspReconciled: false,
    complete: true,
    inplay: false,
    numberOfWinners: 0,
    numberOfRunners: 400,
    numberOfActiveRunners: 400,
    lastMatchTime: "2023-05-18T08:32:48.555Z",
    totalMatched: 24279.87,
    totalAvailable: 8946.46,
    crossMatching: true,
    runnersVoidable: false,
    version: 5251193095,
    runners: [
      {
        selectionId: 39992,
        handicap: 4.5,
        status: "ACTIVE",
        lastPriceTraded: 2.2,
        totalMatched: 0,
        ex: {
          availableToBack: [{ price: 2.1, size: 113.59 }],
          availableToLay: [{ price: 2.22, size: 830.35 }],
          tradedVolume: [],
        },
      },
      {
        selectionId: 39988,
        handicap: -4.5,
        status: "ACTIVE",
        lastPriceTraded: 1.84,
        totalMatched: 0,
        ex: {
          availableToBack: [{ price: 1.82, size: 1012.85 }],
          availableToLay: [{ price: 1.91, size: 124.88 }],
          tradedVolume: [],
        },
      },
      {
        selectionId: 39992,
        handicap: 7.5,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 1.88, size: 113.59 },
            { price: 1.87, size: 88.02 },
            { price: 1.83, size: 60 },
          ],
          availableToLay: [
            { price: 2.16, size: 76.2 },
            { price: 2.22, size: 49.82 },
            { price: 2.24, size: 50.1 },
          ],
          tradedVolume: [],
        },
      },
      {
        selectionId: 39988,
        handicap: -7.5,
        status: "ACTIVE",
        lastPriceTraded: 1.9,
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 1.87, size: 88.02 },
            { price: 1.83, size: 60 },
            { price: 1.81, size: 62 },
          ],
          availableToLay: [
            { price: 2.14, size: 99.79 },
            { price: 2.16, size: 76.2 },
            { price: 2.22, size: 49.82 },
          ],
          tradedVolume: [],
        },
      },
      {
        selectionId: 39992,
        handicap: 8.5,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 1.85, size: 155.95 },
            { price: 1.84, size: 113.59 },
          ],
          availableToLay: [{ price: 2.3, size: 213.41 }],
          tradedVolume: [],
        },
      },
      {
        selectionId: 39988,
        handicap: -8.5,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 1.78, size: 113.59 },
            { price: 1.77, size: 163.09 },
          ],
          availableToLay: [
            { price: 2.18, size: 132.34 },
            { price: 2.2, size: 95 },
          ],
          tradedVolume: [],
        },
      },
      {
        selectionId: 39992,
        handicap: 9.5,
        status: "ACTIVE",
        lastPriceTraded: 2,
        totalMatched: 0,
        ex: {
          availableToBack: [{ price: 1.76, size: 113.59 }],
          availableToLay: [{ price: 1.97, size: 1035.53 }],
          tradedVolume: [],
        },
      },
      {
        selectionId: 39988,
        handicap: -9.5,
        status: "ACTIVE",
        lastPriceTraded: 2,
        totalMatched: 0,
        ex: {
          availableToBack: [{ price: 2.04, size: 1000 }],
          availableToLay: [{ price: 2.32, size: 86.17 }],
          tradedVolume: [],
        },
      },
      {
        selectionId: 39992,
        handicap: 10.5,
        status: "ACTIVE",
        lastPriceTraded: 1.83,
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 1.73, size: 113.59 },
            { price: 1.72, size: 160.03 },
          ],
          availableToLay: [
            { price: 1.91, size: 1099.48 },
            { price: 1.92, size: 45 },
          ],
          tradedVolume: [],
        },
      },
      {
        selectionId: 39988,
        handicap: -10.5,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 2.1, size: 1000 },
            { price: 2.08, size: 41.54 },
          ],
          availableToLay: [
            { price: 2.38, size: 82.56 },
            { price: 2.4, size: 114.68 },
          ],
          tradedVolume: [],
        },
      },
    ],
    keyLineDescription: {
      keyLine: [
        { selectionId: 39992, handicap: 7.5 },
        { selectionId: 39988, handicap: -7.5 },
      ],
    },
    eventName: "Fremantle v Geelong",
  },
  {
    marketName: "Total Points",
    marketId: "1.214006381",
    isMarketDataDelayed: true,
    status: "OPEN",
    betDelay: 0,
    bspReconciled: false,
    complete: true,
    inplay: false,
    numberOfWinners: 0,
    numberOfRunners: 482,
    numberOfActiveRunners: 482,
    lastMatchTime: "2023-05-17T04:13:58.412Z",
    totalMatched: 199.99,
    totalAvailable: 2900.1,
    crossMatching: true,
    runnersVoidable: false,
    version: 5251193497,
    runners: [
      {
        selectionId: 8435233,
        handicap: 160.5,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [{ price: 1.01, size: 100 }],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 8435232,
        handicap: 160.5,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [{ price: 1.01, size: 100 }],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 8435233,
        handicap: 172.5,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [],
          availableToLay: [{ price: 2.34, size: 121.32 }],
          tradedVolume: [],
        },
      },
      {
        selectionId: 8435232,
        handicap: 172.5,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [],
          availableToLay: [{ price: 2.48, size: 118.56 }],
          tradedVolume: [],
        },
      },
      {
        selectionId: 8435233,
        handicap: 173.5,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 1.89, size: 124.87 },
            { price: 1.87, size: 88.02 },
            { price: 1.84, size: 119 },
          ],
          availableToLay: [
            { price: 2.14, size: 248.79 },
            { price: 2.16, size: 76.2 },
            { price: 2.22, size: 98.92 },
          ],
          tradedVolume: [],
        },
      },
      {
        selectionId: 8435232,
        handicap: 173.5,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 1.89, size: 168.3 },
            { price: 1.88, size: 114 },
            { price: 1.87, size: 88.02 },
          ],
          availableToLay: [
            { price: 2.14, size: 110.45 },
            { price: 2.16, size: 76.2 },
            { price: 2.2, size: 99.53 },
          ],
          tradedVolume: [],
        },
      },
    ],
    keyLineDescription: {
      keyLine: [
        { selectionId: 8435232, handicap: 173.5 },
        { selectionId: 8435233, handicap: 173.5 },
      ],
    },
    eventName: "Fremantle v Geelong",
  },
  {
    marketName: "Most Disposals - Group B",
    marketId: "1.214006627",
    isMarketDataDelayed: true,
    status: "OPEN",
    betDelay: 0,
    bspReconciled: false,
    complete: true,
    inplay: false,
    numberOfWinners: 1,
    numberOfRunners: 8,
    numberOfActiveRunners: 8,
    totalMatched: 0,
    totalAvailable: 0,
    crossMatching: false,
    runnersVoidable: false,
    version: 5251193989,
    runners: [],
    eventName: "Fremantle v Geelong",
  },
  {
    marketName: "Same Game Multis",
    marketId: "1.214006632",
    isMarketDataDelayed: true,
    status: "OPEN",
    betDelay: 0,
    bspReconciled: false,
    complete: false,
    inplay: false,
    numberOfWinners: 0,
    numberOfRunners: 9,
    numberOfActiveRunners: 9,
    totalMatched: 0,
    totalAvailable: 2025.91,
    crossMatching: false,
    runnersVoidable: true,
    version: 5251194814,
    runners: [
      {
        selectionId: 56127562,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 3.6, size: 96.15 },
            { price: 3.4, size: 104.17 },
            { price: 3.3, size: 108.7 },
          ],
          availableToLay: [
            { price: 4.9, size: 25 },
            { price: 7, size: 16.67 },
          ],
          tradedVolume: [],
        },
      },
      {
        selectionId: 56127563,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 5.8, size: 52.08 },
            { price: 5.5, size: 55.56 },
            { price: 5.3, size: 58.14 },
          ],
          availableToLay: [{ price: 9.2, size: 28.33 }],
          tradedVolume: [],
        },
      },
      {
        selectionId: 56127564,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 5.2, size: 59.52 },
            { price: 5, size: 62.5 },
            { price: 4.8, size: 65.79 },
          ],
          availableToLay: [{ price: 8.6, size: 31.02 }],
          tradedVolume: [],
        },
      },
      {
        selectionId: 56127565,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 3.2, size: 113.64 },
            { price: 3, size: 125 },
            { price: 2.9, size: 131.58 },
          ],
          availableToLay: [
            { price: 4.5, size: 27.78 },
            { price: 6.6, size: 17.86 },
          ],
          tradedVolume: [],
        },
      },
      {
        selectionId: 56127566,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 4.6, size: 69.44 },
            { price: 4.4, size: 73.53 },
            { price: 4.2, size: 78.12 },
          ],
          availableToLay: [
            { price: 5.9, size: 20 },
            { price: 8, size: 14.29 },
          ],
          tradedVolume: [],
        },
      },
      {
        selectionId: 56127567,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 7.6, size: 37.88 },
            { price: 7.2, size: 40.32 },
            { price: 7, size: 41.67 },
          ],
          availableToLay: [{ price: 13, size: 18.33 }],
          tradedVolume: [],
        },
      },
      {
        selectionId: 56127569,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 11.5, size: 23.81 },
            { price: 11, size: 25 },
            { price: 10.5, size: 26.32 },
          ],
          availableToLay: [{ price: 19, size: 11.81 }],
          tradedVolume: [],
        },
      },
      {
        selectionId: 56127570,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 3.5, size: 100 },
            { price: 3.3, size: 108.7 },
            { price: 3.2, size: 113.64 },
          ],
          availableToLay: [
            { price: 4.8, size: 26.32 },
            { price: 6.8, size: 17.24 },
          ],
          tradedVolume: [],
        },
      },
    ],
    eventName: "Fremantle v Geelong",
  },
  {
    marketName: "20 Disposals or More",
    marketId: "1.214006633",
    isMarketDataDelayed: true,
    status: "OPEN",
    betDelay: 0,
    bspReconciled: false,
    complete: false,
    inplay: false,
    numberOfWinners: 0,
    numberOfRunners: 21,
    numberOfActiveRunners: 21,
    totalMatched: 0,
    totalAvailable: 5865.81,
    crossMatching: false,
    runnersVoidable: false,
    version: 5251194001,
    runners: [
      {
        selectionId: 16630853,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 1.1, size: 718.95 },
            { price: 1.06, size: 1100 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 13076897,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 1.26, size: 267.97 },
            { price: 1.22, size: 314.29 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 7196959,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 1.26, size: 257.21 },
            { price: 1.22, size: 300 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 27123771,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 1.42, size: 160.54 },
            { price: 1.38, size: 178.38 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 5621060,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 1.52, size: 131 },
            { price: 1.46, size: 143.48 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 12440324,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 1.52, size: 128.38 },
            { price: 1.48, size: 140.43 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 39057247,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 1.58, size: 155.59 },
            { price: 1.52, size: 169.23 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 23199474,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 1.72, size: 123.98 },
            { price: 1.66, size: 133.33 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 37484994,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 2.22, size: 73.04 },
            { price: 2.08, size: 81.48 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 5821057,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 2.26, size: 70.56 },
            { price: 2.12, size: 78.57 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 23199473,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 2.32, size: 67.13 },
            { price: 2.18, size: 74.58 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 6146431,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 2.4, size: 80.14 },
            { price: 2.26, size: 88.8 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 8072096,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 2.66, size: 67.27 },
            { price: 2.5, size: 74 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 23184806,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 2.76, size: 63.21 },
            { price: 2.6, size: 69.38 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 27123031,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 2.82, size: 61.36 },
            { price: 2.66, size: 67.27 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 13226966,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 3.6, size: 43.11 },
            { price: 3.3, size: 49.33 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 7279075,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 3.9, size: 38.95 },
            { price: 3.5, size: 44.4 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 13336671,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 4.4, size: 32.65 },
            { price: 4, size: 37 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 14746476,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 4.8, size: 29.76 },
            { price: 4.3, size: 33.64 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 43947673,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 4.9, size: 28.91 },
            { price: 4.4, size: 32.65 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 27957647,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 5.3, size: 26.27 },
            { price: 4.8, size: 29.6 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
    ],
    eventName: "Fremantle v Geelong",
  },
  {
    marketName: "25 Disposals or More",
    marketId: "1.214006634",
    isMarketDataDelayed: true,
    status: "OPEN",
    betDelay: 0,
    bspReconciled: false,
    complete: false,
    inplay: false,
    numberOfWinners: 0,
    numberOfRunners: 10,
    numberOfActiveRunners: 10,
    totalMatched: 0,
    totalAvailable: 1834.62,
    crossMatching: false,
    runnersVoidable: false,
    version: 5251194003,
    runners: [
      {
        selectionId: 27123032,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 1.32, size: 214.22 },
            { price: 1.28, size: 244.44 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 16630853,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 1.38, size: 178.43 },
            { price: 1.34, size: 200 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 13076897,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 2.04, size: 85.01 },
            { price: 1.92, size: 95.65 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 7196959,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 2.08, size: 81.66 },
            { price: 1.96, size: 91.67 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 27123771,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 2.34, size: 83.33 },
            { price: 2.2, size: 92.5 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 12440324,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 2.66, size: 67.27 },
            { price: 2.5, size: 74 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 5621060,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 3.4, size: 47.13 },
            { price: 3.1, size: 54.15 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 39057247,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 3.6, size: 43.11 },
            { price: 3.3, size: 49.33 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 23199474,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 4.2, size: 34.91 },
            { price: 3.8, size: 39.64 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 37484994,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 5.1, size: 27.34 },
            { price: 4.6, size: 30.83 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
    ],
    eventName: "Fremantle v Geelong",
  },
  {
    marketName: "30 Disposals or More",
    marketId: "1.214006635",
    isMarketDataDelayed: true,
    status: "OPEN",
    betDelay: 0,
    bspReconciled: false,
    complete: false,
    inplay: false,
    numberOfWinners: 0,
    numberOfRunners: 6,
    numberOfActiveRunners: 6,
    totalMatched: 0,
    totalAvailable: 576.57,
    crossMatching: false,
    runnersVoidable: false,
    version: 5251194005,
    runners: [
      {
        selectionId: 27123032,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 2.12, size: 79.32 },
            { price: 2, size: 88.89 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 16630853,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 2.22, size: 73.04 },
            { price: 2.08, size: 81.48 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 7196959,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 4.4, size: 32.65 },
            { price: 4, size: 37 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 13076897,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 4.4, size: 32.65 },
            { price: 4, size: 37 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 27123771,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 4.8, size: 29.76 },
            { price: 4.3, size: 33.64 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 12440324,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 5.7, size: 24.08 },
            { price: 5.1, size: 27.07 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
    ],
    eventName: "Fremantle v Geelong",
  },
  {
    marketName: "Total Points Line",
    marketId: "1.214006636",
    isMarketDataDelayed: true,
    status: "OPEN",
    betDelay: 0,
    bspReconciled: false,
    complete: true,
    inplay: false,
    numberOfWinners: 0,
    numberOfRunners: 1,
    numberOfActiveRunners: 1,
    totalMatched: 0,
    totalAvailable: 136.3,
    crossMatching: false,
    runnersVoidable: false,
    version: 5251194007,
    runners: [
      {
        selectionId: 40875,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [{ price: 48, size: 136.3 }],
          availableToLay: [],
          tradedVolume: [],
        },
      },
    ],
    eventName: "Fremantle v Geelong",
  },
  {
    marketName: "15 Disposals or More",
    marketId: "1.214006637",
    isMarketDataDelayed: true,
    status: "OPEN",
    betDelay: 0,
    bspReconciled: false,
    complete: false,
    inplay: false,
    numberOfWinners: 0,
    numberOfRunners: 35,
    numberOfActiveRunners: 35,
    totalMatched: 0,
    totalAvailable: 13800.64,
    crossMatching: false,
    runnersVoidable: false,
    version: 5251194009,
    runners: [
      {
        selectionId: 5621060,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 1.1, size: 718.95 },
            { price: 1.06, size: 1100 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 39057247,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 1.12, size: 646.43 },
            { price: 1.08, size: 942.86 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 27123771,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 1.12, size: 587.19 },
            { price: 1.08, size: 825 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 23199474,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 1.14, size: 496.24 },
            { price: 1.1, size: 660 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 12440324,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 1.16, size: 460.57 },
            { price: 1.12, size: 600 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 23199473,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 1.26, size: 257.21 },
            { price: 1.22, size: 300 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 6146431,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 1.28, size: 238.1 },
            { price: 1.24, size: 275 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 23184806,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 1.32, size: 207.29 },
            { price: 1.28, size: 235.71 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 37484994,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 1.34, size: 194.69 },
            { price: 1.3, size: 220 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 8072096,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 1.36, size: 183.54 },
            { price: 1.32, size: 206.25 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 5821057,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 1.38, size: 178.43 },
            { price: 1.34, size: 200 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 7279075,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 1.58, size: 152.8 },
            { price: 1.54, size: 166.04 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 27123031,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 1.62, size: 145.02 },
            { price: 1.56, size: 157.14 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 13336671,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 1.66, size: 133.68 },
            { price: 1.62, size: 144.26 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 13226966,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 1.66, size: 133.68 },
            { price: 1.62, size: 144.26 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 27957647,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 1.72, size: 123.98 },
            { price: 1.66, size: 133.33 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 14746476,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 1.74, size: 120.48 },
            { price: 1.68, size: 129.41 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 43947673,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 1.76, size: 118.81 },
            { price: 1.7, size: 127.54 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 41859360,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 1.98, size: 91.57 },
            { price: 1.86, size: 103.53 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 13049516,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 2.06, size: 84.15 },
            { price: 1.94, size: 94.62 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 10646048,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 2.22, size: 73.04 },
            { price: 2.08, size: 81.48 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 8818704,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 2.28, size: 68.8 },
            { price: 2.16, size: 76.52 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 19651142,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 2.32, size: 67.13 },
            { price: 2.18, size: 74.58 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 25207396,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 2.44, size: 77.19 },
            { price: 2.3, size: 85.38 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 2379345,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 2.44, size: 77.19 },
            { price: 2.3, size: 85.38 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 28037126,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 2.66, size: 67.27 },
            { price: 2.5, size: 74 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 23736959,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 2.72, size: 65.18 },
            { price: 2.56, size: 71.61 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 17654140,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 2.82, size: 61.36 },
            { price: 2.66, size: 67.27 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 13381134,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 3.4, size: 47.13 },
            { price: 3.1, size: 54.15 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 39942863,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 3.5, size: 46.06 },
            { price: 3.1, size: 52.86 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 11828449,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 3.6, size: 44.05 },
            { price: 3.2, size: 50.45 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 3955520,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 3.6, size: 44.05 },
            { price: 3.2, size: 50.45 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 17796622,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 4.2, size: 34.91 },
            { price: 3.8, size: 39.64 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 18834071,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 4.3, size: 33.74 },
            { price: 3.9, size: 38.28 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
      {
        selectionId: 10156306,
        handicap: 0,
        status: "ACTIVE",
        totalMatched: 0,
        ex: {
          availableToBack: [
            { price: 5.4, size: 25.28 },
            { price: 4.9, size: 28.46 },
          ],
          availableToLay: [],
          tradedVolume: [],
        },
      },
    ],
    eventName: "Fremantle v Geelong",
  },
];
