export enum AFLTeam {
  ADELAIDE = "adelaide",
  BRISBANE = "brisbane",
  CARLTON = "carlton",
  COLLINGWOOD = "collingwood",
  ESSENDON = "essendon",
  FREMANTlE = "fremantle",
  GEELONG = "geelong",
  GOLDCOAST = "gold coast",
  GREATER_WESTERN_SYDNEY = "greater western sydney",
  HAWTHORN = "hawthorn",
  MELBOURNE = "melbourne",
  NORTH_MELBOURNE = "north melbourne",
  PORT_ADELAIDE = "port adelaide",
  RICHMOND = "richmond",
  ST_KILDA = "st kilda",
  SYDNEY_SWANS = "sydney",
  WEST_COAST_EAGLES = "west coast eagles",
  WESTERN_BULLDOGS = "western bulldogs",
}
